const CountryDataActionTypes = {
  FETCH_COUNTRYDATA_START: 'FETCH_COUNTRYDATA_START',
  FETCH_COUNTRYDATA_SUCCESS: 'FETCH_COUNTRYDATA_SUCCESS',
  FETCH_COUNTRYDATA_FAILURE: 'FETCH_COUNTRYDATA_FAILURE',
}

export default CountryDataActionTypes
