const DailyDataActionTypes = {
  FETCH_DAILYDATA_START: 'FETCH_DAILYDATA_START',
  FETCH_DAILYDATA_SUCCESS: 'FETCH_DAILYDATA_SUCCESS',
  FETCH_DAILYDATA_FAILURE: 'FETCH_DAILYDATA_FAILURE',
}

export default DailyDataActionTypes
