export { default as About } from './About/About'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as News } from './News/News'
export { default as Bangladesh } from './Bangladesh/Bangladesh'
export { default as Map } from './Map/Map'
