const GlobalDataActionTypes = {
  FETCH_GLOBALDATA_START: 'FETCH_GLOBALDATA_START',
  FETCH_GLOBALDATA_SUCCESS: 'FETCH_GLOBALDATA_SUCCESS',
  FETCH_GLOBALDATA_FAILURE: 'FETCH_GLOBALDATA_FAILURE',
}

export default GlobalDataActionTypes
