const AllDataActionTypes = {
  FETCH_ALL_DATA_START: 'FETCH_ALL_DATA_START',
  FETCH_ALL_DATA_SUCCESS: 'FETCH_ALL_DATA_SUCCESS',
  FETCH_ALL_DATA_FAILURE: 'FETCH_ALL_DATA_FAILURE',
}

export default AllDataActionTypes
